# Generated by Django 4.2.3 on 2023-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Super user', 'verbose_name_plural': 'Super users'},
        ),
        migrations.AddField(
            model_name='user',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
