# Generated by Django 4.2.3 on 2023-07-20 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_update',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
