# Generated by Django 4.2.3 on 2023-07-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_rename_book_id_purchase_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-data']},
        ),
    ]
