# Generated by Django 4.2.3 on 2023-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
