version: '3.8'

services:
  flask_app:
    build: "."

    ports:
     - "4200:4200"
    environment:
      - DB_TYPE=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
     - db

  db:
    image: postgres:14
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
     - "5432:5432"

  nginx:
   image: nginx:1.19.0
   ports:
    - "80:80"
   volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  postgres_data: